In [1]:
from pydeseq2.dds import DeseqDataSet
from pydeseq2.ds import DeseqStats

import pandas as pd

In [2]:
counts = pd.read_csv('DEGs//EC_Intima_pb.csv', index_col=0)
counts

,0,1,2,3,4,5,6,7,8,9,...,338,339,340,341,342,343,condition,plaque_region,cell_type,pseudobulk_sample
Intima_diseased,1.0,3.0,0.0,0.0,0.0,3.0,2.0,1.0,0.0,0.0,...,1.0,0.0,3.0,4.0,0.0,1.0,diseased,Intima,EC,Intima_diseased_replicate_1
Intima_diseased,2.0,6.0,0.0,0.0,1.0,3.0,1.0,2.0,0.0,0.0,...,0.0,0.0,1.0,2.0,0.0,1.0,diseased,Intima,EC,Intima_diseased_replicate_2
Intima_diseased,0.0,3.0,1.0,0.0,0.0,5.0,1.0,3.0,0.0,0.0,...,0.0,0.0,0.0,3.0,0.0,2.0,diseased,Intima,EC,Intima_diseased_replicate_3
Intima_healthy,60.0,42.0,3.0,14.0,4.0,311.0,2.0,2.0,1.0,4.0,...,4.0,8.0,71.0,59.0,2.0,8.0,healthy,Intima,EC,Intima_healthy_replicate_1
Intima_healthy,57.0,34.0,2.0,12.0,4.0,317.0,7.0,1.0,1.0,3.0,...,10.0,5.0,81.0,69.0,2.0,3.0,healthy,Intima,EC,Intima_healthy_replicate_2
Intima_healthy,67.0,45.0,7.0,20.0,4.0,216.0,15.0,1.0,3.0,6.0,...,3.0,9.0,69.0,100.0,3.0,4.0,healthy,Intima,EC,Intima_healthy_replicate_3

In [3]:
metadata = pd.DataFrame(zip(counts.index, counts["condition"]),
                        columns = ['Sample', 'Condition'])
metadata = metadata.set_index('Sample')
metadata

                Condition
Sample
Intima_diseased  diseased
Intima_diseased  diseased
Intima_diseased  diseased
Intima_healthy    healthy
Intima_healthy    healthy
Intima_healthy    healthy

In [4]:
counts = counts.iloc[:,:-4]
counts

,0,1,2,3,4,5,6,7,8,9,...,334,335,336,337,338,339,340,341,342,343
Intima_diseased,1.0,3.0,0.0,0.0,0.0,3.0,2.0,1.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,3.0,4.0,0.0,1.0
Intima_diseased,2.0,6.0,0.0,0.0,1.0,3.0,1.0,2.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0,0.0,1.0
Intima_diseased,0.0,3.0,1.0,0.0,0.0,5.0,1.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,2.0
Intima_healthy,60.0,42.0,3.0,14.0,4.0,311.0,2.0,2.0,1.0,4.0,...,6.0,2.0,0.0,75.0,4.0,8.0,71.0,59.0,2.0,8.0
Intima_healthy,57.0,34.0,2.0,12.0,4.0,317.0,7.0,1.0,1.0,3.0,...,1.0,4.0,0.0,56.0,10.0,5.0,81.0,69.0,2.0,3.0
Intima_healthy,67.0,45.0,7.0,20.0,4.0,216.0,15.0,1.0,3.0,6.0,...,8.0,1.0,2.0,68.0,3.0,9.0,69.0,100.0,3.0,4.0

In [5]:
dds = DeseqDataSet(counts=counts,
            metadata=metadata,
            design_factors="Condition")

c:\Users\laure\anaconda3\envs\cluster_var\lib\site-packages\anndata\_core\anndata.py:1818: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

In [11]:
dds.deseq2()

Fitting size factors...
... done in 0.00 seconds.

Fitting dispersions...

TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.